### ISSUE TITLE
Update format's branding

### ISSUE THREAD

**Issue by aeden** [aetrion/dnsimple-services#20]
See http://format.com/

**Comment by sbastn** [comment]
Done here: https://github.com/aetrion/dnsimple-services/commit/65d24d1a170177f7b86f61aeb3668d0903d1d2cc

**Comment by weppos** [comment]
@sbastn that commit was then reverted by me in https://github.com/aetrion/dnsimple-services/commit/5962cf5df8ecd96163ff6755150bbd9d6b35673a

The reason is because we can't delete nor change a service name as of today, or things we'll break in our backend. There is an open issue we need to fix.

I'm reopening this issue.

**Comment by weppos** [comment]
Also note the flag `requires-internal-support` I added a while ago to flag issues we can't close/merge as of today because of such issue.

**Comment by sbastn** [comment]
Got it, I thought it was just a logo refresh like I did in https://github.com/aetrion/dnsimple-services/pull/40
